### ISSUE TITLE
master: Application stuck on the welcome screen

### ISSUE THREAD

**Issue by uajain** [ghk/sideka-electron#2]
Trying to flatpak-ify Sideka but looks like the app is stuck on the welcome screen in the flatpak sandbox.

Also while building and running normally (outside the sandbox), I see the similar issue (it's stuck). So, I am filing this considering that this is not a flatpak-related issue. Can someone look into it?

sideka-electron > yarn run launch
yarn run v1.5.1
warning package.json: "dependencies" has dependency "shapefile" with range "^0.6.5" that collides with a dependency in "devDependencies" of the same name with version "^0.6.6"
$ electron ./dist
[02:26:52.670] [info] Checking for update
[02:26:52.679] [info] checking-for-update
[02:26:54.789] [error] Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/html; charset=utf-8"
  ],
  "date": [
    "Thu, 10 May 2018 20:56:54 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 10 May 2038 20:56:54 -0000; secure; HttpOnly",
    "_gh_sess=cHZOYzlOcStJdGN0WmQ1WU00WldGc25RcjExdWI4T3NVYkovRUp5Zmgzb0hJNnUrSnZHNXRoanlOeHZ1azJJdTJpTmlab3BUeU5HM09iOXZjZXpnVXlQczl2a1poUWNwOHl3NkZVN1hRakhkSXRpK2kvYjQxc1BCZ3g3OTgvdGVwQzJMSGwwcjh0ekFrRFhwYTBSK05ONTByU1QyVWk2bmlEZ0VEdm0wSGFuOUFLdzZ3Yk1SYXhKRzdEcWNqS0xNMlpXcGxSMlI2dXJPWnYxWTVQQXFSUT09LS1pOFNhSTRSQUdSd25SZjNsQkxLekh3PT0%3D--992ed040844d68ed5cef9ad24d0d0a595e91c695; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "97E2:4FBC:A134A7:1334A2A:5AF4B216"
  ],
  "x-request-id": [
    "68b8ec32-442d-4d82-9899-bebb544b8d9f"
  ],
  "x-runtime": [
    "0.059280"
  ],
  "x-runtime-rack": [
    "0.067869"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at createHttpError (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/home/uajain/sideka-electron/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at CancellationToken.createPromise (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/GitHubProvider.ts:74:38
From previous event:
    at GitHubProvider.getLatestVersion (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/home/uajain/sideka-electron/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at createHttpError (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/home/uajain/sideka-electron/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
    at CancellationToken.createPromise (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/GitHubProvider.ts:74:38
    at GitHubProvider.getLatestVersion (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater.getUpdateInfo (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
    at AppImageUpdater.doCheckForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater._checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/home/uajain/sideka-electron/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at newError (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/index.ts:23:17)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/GitHubProvider.ts:78:15
    at Generator.throw (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/home/uajain/sideka-electron/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
[02:26:54.790] [error] Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/html; charset=utf-8"
  ],
  "date": [
    "Thu, 10 May 2018 20:56:54 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "logged_in=no; domain=.github.com; path=/; expires=Mon, 10 May 2038 20:56:54 -0000; secure; HttpOnly",
    "_gh_sess=cHZOYzlOcStJdGN0WmQ1WU00WldGc25RcjExdWI4T3NVYkovRUp5Zmgzb0hJNnUrSnZHNXRoanlOeHZ1azJJdTJpTmlab3BUeU5HM09iOXZjZXpnVXlQczl2a1poUWNwOHl3NkZVN1hRakhkSXRpK2kvYjQxc1BCZ3g3OTgvdGVwQzJMSGwwcjh0ekFrRFhwYTBSK05ONTByU1QyVWk2bmlEZ0VEdm0wSGFuOUFLdzZ3Yk1SYXhKRzdEcWNqS0xNMlpXcGxSMlI2dXJPWnYxWTVQQXFSUT09LS1pOFNhSTRSQUdSd25SZjNsQkxLekh3PT0%3D--992ed040844d68ed5cef9ad24d0d0a595e91c695; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "97E2:4FBC:A134A7:1334A2A:5AF4B216"
  ],
  "x-request-id": [
    "68b8ec32-442d-4d82-9899-bebb544b8d9f"
  ],
  "x-runtime": [
    "0.059280"
  ],
  "x-runtime-rack": [
    "0.067869"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at createHttpError (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/home/uajain/sideka-electron/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at CancellationToken.createPromise (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/GitHubProvider.ts:74:38
From previous event:
    at GitHubProvider.getLatestVersion (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/home/uajain/sideka-electron/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at createHttpError (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:31:10)
    at ElectronHttpExecutor.handleResponse (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:122:7)
    at ClientRequest.request.doRequest.response (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:84:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/home/uajain/sideka-electron/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
    at CancellationToken.createPromise (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/CancellationToken.ts:51:5)
    at ElectronHttpExecutor.doApiRequest (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:81:30)
    at ElectronHttpExecutor.request (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/httpExecutor.ts:73:17)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/GitHubProvider.ts:74:38
    at GitHubProvider.getLatestVersion (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater.getUpdateInfo (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
    at AppImageUpdater.doCheckForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppImageUpdater._checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/home/uajain/sideka-electron/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
    at newError (/home/uajain/sideka-electron/dist/node_modules/builder-util-runtime/src/index.ts:23:17)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/GitHubProvider.ts:78:15
    at Generator.throw (<anonymous>)
From previous event:
    at GitHubProvider.getLatestVersion (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/GitHubProvider.js:167:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:304:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:460:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:308:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:502:7)
    at /home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:279:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/out/AppUpdater.js:433:7)
    at AppImageUpdater.checkForUpdates (/home/uajain/sideka-electron/dist/node_modules/electron-updater/src/AppUpdater.ts:217:35)
    at WebContents.<anonymous> (/home/uajain/sideka-electron/dist/index.js:1:3672)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

Application is stuck on the welcome screen at the startup.
node v8.11.0

Flathub issue: https://github.com/flathub/id.sideka.App/issues/1

**Comment by ghk** [comment]
Hello, we'll take a look when we test it on linux next week. I got no dev linux machine on me, unfortunately.

**Comment by uajain** [comment]
@ghk thanks! 

I wonder if the server side is creating problems here. In the initial part of the log : https://github.com/ghk/sideka_app_server/releases/download/v2.2.0/latest-linux.yml is a invalid URL. 

I also tried building from source on a windows machine and it ran just fine. So, I assume you use windows as the base OS from development.

**Comment by uajain** [comment]
@ghk Hi there,

I tried to patch  out the auto updater(`electron-updater`) part (as flatpak dir are `read-only` and any updates won't work anyway) and that suppress the log (above). Therefore, still the problem remains that the app is stuck on the welcome screen and never proceeds to login pag. This is very specific to building on linux.

**Comment by ghk** [comment]
Hello, I've fixed the linux build problem, FYI we run it by "npm start" instead of "yarn run launch"

**Comment by uajain** [comment]
Perfect. Thank you @ghk for your support. Closing.
